lists:
  - name: confidence_level_required
    items:
      - text: None
        value: none
        hint: You might not need to check a user's identity if your service only lets users sign in to an account.
      - text: Low confidence
        value: low
        hint: You'll need this if your service lets users view or update personal information.
      - text: Medium confidence
        value: medium
        hint: You'll need this if your services gives users access to sensitive information, money or benefits.
      - text: High confidence
        value: high
        hint: You'll need this if your service gives users access to secure buildings, like a nuclear power station.
      - text: You're not sure
        value: not_sure
  - name: org_check_method
    items:
      - text: Using their own identity checking process
        value: own
      - text: By checking the person's details with an authoritative source
        value: authoritative_source
      - text: Using a process that met the requirements in the Money Laundering Regulations 2017
        value: money_laundering_regulations_2017
      - text: By physically comparing them to an image of the person they're claiming to be from an authoritative source
        value: physically_comparing
  - name: activity_time_period
    items:
      - text: The last 3 years
        value: 36_months
      - text: The last 12 months
        value: 12_months
      - text: The last 6 months
        value: 6_months
      - text: The last 3 months
        value: 3_months
  - name: identity_stolen_fraud
    items:
      - text: The person has not had their details stolen (even if those details have not been used fraudulently yet)
        value: not_had_details_stolen
      - text: The person's identity has not been reported as stolen
        value: not_reported_stolen
      - text: The person is not at a high risk of being impersonated (for example if they’re a ‘politically exposed person’, like a politician or a judge)
        value: not_high_risk_impersonated
      - text: The person's details do not belong to someone who has died
        value: details_not_belong_to_somone_who_died
      - text: The person's details are known by an organisation that should have a record of that person (for example an Electoral Registration Office in a local authority)
        value: record_of_person
      - text: None of these things
        value: none
  - name: counter_fraud_data_sources
    items:
      - text: One
        value: one
      - text: More than one
        value: more_than_one
